# Generated by Django 3.1.6 on 2021-02-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('book', models.CharField(max_length=100)),
                ('date_of_issue', models.DateField()),
                ('return_date', models.DateField()),
            ],
        ),
    ]
